# line to define a global platform for your project
# platform :ios, '6.0'
platform :ios, '7.0'
target ‘SetTheCacheHtml’ do
    
pod 'AFNetworking','3.1.0'
pod 'SDWebImage', '~> 3.7.3'
pod 'FileMD5Hash', '~> 2.0.0'
end

target ‘SetTheCacheHtmlTests' do

end
